---
title: Efficiency measurement and benchmarking
author: ''
date: '2022-01-22'
slug: efficiency-measurement-and-benchmarking
categories:
  - Project Work
  - R
tags:
  - machine learning
  - classification
  - logistic regression
  - decision tree
  - nonparametric statistics
  - DEA
  - benchmarking
subtitle: 'Implementing a management control system to improve the timeliness of technical support service.'
summary: 'Implementing a management control system to improve the timeliness of technical support service.'
authors: []
image:
  caption: 'Image credit:[**Unsplash**](https://unsplash.com/photos/vnOAErpxhZ4)'
  focal_point: ''
  preview_only: no
projects: []
toc: true
---


## Introduction

This project was carried out during my internship experience at [Newteam Srl](https://www.newteam.it/), a company specialized in the development of software for ticket management related to technical support activities.

Many companies now rely on automated systems for ticket management, in order to monitor in real time the requests for technical assistance of their customers and act effectively in solving their problems. This not only strengthens the Customer Care and [CRM](https://en.wikipedia.org/wiki/Customer_relationship_management) process, but also improves the organizational structure of the human resources involved in managing the service, both in the case of remote assistance via help desk and when the presence of a technician in the field is required.

My task was to analyse the performance, in terms of efficiency, of the tickets managed by a Newteam client, using parametric and non-parametric statistical methods, with the aim of:

- building a benchmarking system to compare efficiency between different technicians and geographical areas. To estimate efficiency, the DEA ([Data Envelopment Analysis](https://en.wikipedia.org/wiki/Data_envelopment_analysis)) method was used.

- identifying the factors that influenced the overall timeliness of each ticket and predicting future ticket outcomes, using machine learning methods for classification: [logistic regression](https://en.wikipedia.org/wiki/Logistic_regression) and [decision trees](https://en.wikipedia.org/wiki/Decision_tree).


{{% callout note %}}
Not yet published, it will be available soon.
{{% /callout %}}








